
import { UserRole } from './types';

export const FLAVOURS = [
  "Almond Flaks Roast",
  "Almond Cream",
  "ALMOND FLAKES",
  "ALMOND WHOLE",
  "Alpine Cream",
  "BISCOFE COOKIE",
  "Biscoff Cream",
  "Black forest Cream",
  "Black Gel",
  "Blueberry Cream",
  "Butter scotch nogha",
  "Butterscotch Cream",
  "Caramel Cream",
  "Choco bliss Cream",
  "Choco Crispy boll",
  "Choco Crispy Cream",
  "Choco mouse Cream",
  "Choco Nuts Cream",
  "Chocochips Crispy Royal Cream",
  "Chocotella Cream",
  "Coffee Cream",
  "COLOR BLACK",
  "COLOR BLACK Oreo",
  "COLOR BLUE",
  "COLOR BROWN",
  "COLOR GREEN (POWDER)",
  "COLOR LEMON YELLOW",
  "COLOR ORANGE",
  "COLOR PINK",
  "COLOR RED",
  "crunch chocolate",
  "Dark chocochips",
  "DESSERT FILL CREAM",
  "Devils Delight Cream",
  "Dutch",
  "FANCY STRAND CHOC. (10 kg)",
  "Fresh grapes",
  "Fresh Kiwi",
  "Fresh Mix Fruit",
  "Fresh peach",
  "Fresh pineapple",
  "GULAB JAMUN pieces",
  "Hazelnut Cream",
  "kaju tukda",
  "kajukatli Cream",
  "kajukatli pieces",
  "kalakand chocolate",
  "Kalakand Cream",
  "kalakand pieces",
  "Kiwi Cream",
  "Malai burffi Cream",
  "malai burffi pieces",
  "mango chocolate",
  "Mango Cream",
  "MANGO FRUIT FILLING",
  "Marble Cream",
  "Milk Marble Cream",
  "Mix Fruit Cream",
  "neutral gel",
  "Orange Cream",
  "Oreo Cream",
  "PALM OIL",
  "Pineapple chura",
  "pineapple Cream",
  "PINEAPPLE GEL",
  "Pista Cream",
  "Pista Flaks",
  "Princess Cream",
  "Rainbow Cream",
  "Rasmalai boll",
  "Rasmalai Cream",
  "Raspberry Cream",
  "Red cherry",
  "Red Velvet Cream",
  "rose petal",
  "Salted Caramel Cream",
  "STRAW. GEL (2.5 kg)",
  "Strawberry Cream",
  "Topping Rich",
  "Truffle Cream",
  "Vanilla Cream",
  "White Butter cream",
  "White Chocochips",
  "white chocolate",
  "White Forest Cream",
  "White Gel",
  "white Velvet Cream",
  "Whole Hazelnut"
];

export const MOCK_USERS = [
  { id: '1', username: 'sp_sup', role: UserRole.SP_SUPERVISOR, department: 'SP' },
  { id: '2', username: 'sp_hod', role: UserRole.SP_HOD, department: 'SP' },
  { id: '3', username: 'prod_mgr', role: UserRole.PRODUCTION_MANAGER, department: 'MANAGEMENT' },
  { id: '4', username: 'admin', role: UserRole.ADMIN, department: 'MANAGEMENT' },
  { id: '5', username: 'bms_user', role: UserRole.BMS_USER, department: 'BMS' },
];
